In [1]:
import numpy as np


In [2]:
x=np.zeros((3,4))

In [3]:
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x=np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [1]:
import numpy as np


In [2]:
x=np.zeros((3,4))

In [3]:
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x=np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
x=np.arange(10,25,5)
x


array([10, 15, 20])

In [6]:
x=np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
x=np.full((2,2),7)
x

array([[7, 7],
       [7, 7]])

In [8]:
x=np.random.random((2,2))
x

array([[0.78347484, 0.49224021],
       [0.80801189, 0.99491814]])

In [9]:
x=np.eye(2,2)
x


array([[1., 0.],
       [0., 1.]])

In [10]:
x=np.array(((1,2,3),
            (4,5,6)))
x


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x_T


<class 'NameError'>: name 'x_T' is not defined

In [12]:
x_T

<class 'NameError'>: name 'x_T' is not defined

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=a+b 


In [14]:
x


array([5, 7, 9])

In [15]:
a=np.array([1,2,3,4,5,6])
x=np.split(a,2)

In [16]:
x


[array([1, 2, 3]), array([4, 5, 6])]

In [1]:
import numpy as np


In [2]:
x=np.zeros((3,4))

In [3]:
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x=np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
x=np.arange(10,25,5)
x


array([10, 15, 20])

In [6]:
x=np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
x=np.full((2,2),7)
x

array([[7, 7],
       [7, 7]])

In [8]:
x=np.random.random((2,2))
x

array([[0.78347484, 0.49224021],
       [0.80801189, 0.99491814]])

In [9]:
x=np.eye(2,2)
x


array([[1., 0.],
       [0., 1.]])

In [10]:
x=np.array(((1,2,3),
            (4,5,6)))
x


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x_T


<class 'NameError'>: name 'x_T' is not defined

In [12]:
x_T

<class 'NameError'>: name 'x_T' is not defined

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=a+b 


In [14]:
x


array([5, 7, 9])

In [15]:
a=np.array([1,2,3,4,5,6])
x=np.split(a,2)

In [16]:
x


[array([1, 2, 3]), array([4, 5, 6])]

In [1]:
import numpy as np


In [2]:
x=np.zeros((3,4))

In [3]:
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x=np.ones((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
x=np.arange(10,25,5)
x


array([10, 15, 20])

In [6]:
x=np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
x=np.full((2,2),7)
x

array([[7, 7],
       [7, 7]])

In [8]:
x=np.random.random((2,2))
x

array([[0.78347484, 0.49224021],
       [0.80801189, 0.99491814]])

In [9]:
x=np.eye(2,2)
x


array([[1., 0.],
       [0., 1.]])

In [10]:
x=np.array(((1,2,3),
            (4,5,6)))
x


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x_T


<class 'NameError'>: name 'x_T' is not defined

In [12]:
x_T

<class 'NameError'>: name 'x_T' is not defined

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=a+b 


In [14]:
x


array([5, 7, 9])

In [15]:
a=np.array([1,2,3,4,5,6])
x=np.split(a,2)

In [16]:
x


[array([1, 2, 3]), array([4, 5, 6])]

In [5]:
x=np.arange(10,25,5)
x


array([10, 15, 20])

In [6]:
x=np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
x=np.full((2,2),7)
x

array([[7, 7],
       [7, 7]])

In [8]:
x=np.random.random((2,2))
x

array([[0.78347484, 0.49224021],
       [0.80801189, 0.99491814]])

In [9]:
x=np.eye(2,2)
x


array([[1., 0.],
       [0., 1.]])

In [10]:
x=np.array(((1,2,3),
            (4,5,6)))
x


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x_T


<class 'NameError'>: name 'x_T' is not defined

In [12]:
x_T

<class 'NameError'>: name 'x_T' is not defined

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=a+b 


In [14]:
x


array([5, 7, 9])

In [15]:
a=np.array([1,2,3,4,5,6])
x=np.split(a,2)

In [16]:
x


[array([1, 2, 3]), array([4, 5, 6])]